apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx-test
spec:
  image: "emqx:5.1"
  coreTemplate:
    spec:
      replicas: 2
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
      volumeClaimTemplates:
      ## more information about storage classes: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
        accessModes:
        - ReadWriteOnce
  replicantTemplate:
    spec:
      replicas: 3
      resources:
        requests:
          cpu: 250m
          memory: 1Gi    
      # volumeClaimTemplates:
      # ## more information about storage classes: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses
      #   storageClassName: standard
      #   resources:
      #     requests:
      #       storage: 10Gi
      #   accessModes:
      #   - ReadWriteOnce              
  dashboardServiceTemplate:
    spec:
      ## more information about load balancer: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
      type: LoadBalancer
  listenersServiceTemplate:
    spec:
      ## more information about load balancer: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
      type: LoadBalancer